with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vxy-bash
          template: classic
          base: header, repositories
          config_timezone: Europe/Berlin
          theme: terminal  # <--- Sieht viel krasser aus
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes # Zeigt wie viele Zeilen Code du geschrieben hast
          plugin_habits: yes # Zeigt deine aktivsten Zeiten
          plugin_habits_charts: yes
          plugin_introduction: yes # Kurze Bio-Stats